"""Email notification — sends LinkedIn draft posts via Resend."""

from __future__ import annotations

import logging
import re
from datetime import datetime

import resend

from app.config import AppConfig

logger = logging.getLogger("linkedin.notify")


def send_drafts_email(
    topic: str,
    drafts: list[str],
    config: AppConfig,
) -> None:
    """Send draft LinkedIn posts via Resend for approval."""
    if not config.resend_api_key:
        logger.info("No RESEND_API_KEY set — skipping email")
        return
    if not config.resend_from_email:
        print("[EMAIL] No RESEND_FROM_EMAIL set — skipping email")
        return
    if not config.resend_to_email:
        print("[EMAIL] No RESEND_TO_EMAIL set — skipping email")
        return

    resend.api_key = config.resend_api_key

    date_str = datetime.now().strftime("%B %d, %Y")
    days = ", ".join(config.posting.days)

    # Build draft sections
    draft_sections = ""
    for idx, draft in enumerate(drafts):
        label = chr(65 + idx)  # A, B, C...
        draft_html = _post_to_html(draft)
        draft_sections += f"""
        <div style="padding:24px 32px;background:#fff;border:1px solid #e5e7eb;{'' if idx == 0 else 'border-top:none;'}">
            <h2 style="font-size:18px;color:#0a66c2;margin:0 0 16px 0;">Option {label}</h2>
            <div style="font-size:15px;line-height:1.8;color:#1a1a1a;white-space:pre-wrap;">{draft_html}</div>
        </div>
        """

    html = f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:700px;margin:0 auto;color:#1a1a1a;">
        <div style="background:linear-gradient(135deg,#0a66c2,#004182);padding:24px 32px;border-radius:8px 8px 0 0;">
            <h1 style="color:white;margin:0;font-size:22px;">LinkedIn Draft for Review</h1>
            <p style="color:#b3d4fc;margin:4px 0 0 0;font-size:14px;">{date_str} &middot; Topic: {topic}</p>
        </div>

        <div style="padding:16px 32px;background:#f0f7ff;border:1px solid #e5e7eb;border-top:none;">
            <p style="margin:0;font-size:14px;color:#444;">
                Pick your favorite, edit as needed, and post to LinkedIn.
                <br>Suggested posting days: <strong>{days}</strong>
            </p>
        </div>

        {draft_sections}

        <div style="padding:16px 32px;background:#f8fafc;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;font-size:12px;color:#6b7280;">
            Generated by LinkedIn Post Automation &middot; Powered by Agentway
        </div>
    </div>
    """

    try:
        result = resend.Emails.send({
            "from": config.resend_from_email,
            "to": config.resend_to_email,
            "subject": f"LinkedIn Draft — {topic} ({date_str})",
            "html": html,
        })
        email_id = result.get("id", "ok") if isinstance(result, dict) else str(result)
        print(f"[EMAIL] Sent successfully: {email_id} -> {', '.join(config.resend_to_email)}")
    except Exception as e:
        print(f"[EMAIL] Failed to send: {e}")


def send_topics_email(
    topics: list[dict],
    config: AppConfig,
) -> None:
    """Send suggested topics list via Resend."""
    if not config.resend_api_key:
        logger.info("No RESEND_API_KEY set — skipping email")
        return
    if not config.resend_from_email:
        print("[EMAIL] No RESEND_FROM_EMAIL set — skipping email")
        return
    if not config.resend_to_email:
        print("[EMAIL] No RESEND_TO_EMAIL set — skipping email")
        return

    resend.api_key = config.resend_api_key

    date_str = datetime.now().strftime("%B %d, %Y")

    topic_rows = ""
    for t in topics:
        topic_rows += f"""
        <tr>
            <td style="padding:12px 16px;border-bottom:1px solid #eee;">
                <strong style="color:#0a66c2;">{t.get('topic', '')}</strong>
                <br><span style="font-size:13px;color:#444;">{t.get('angle', '')}</span>
                <br><em style="font-size:12px;color:#888;">{t.get('why_timely', '')}</em>
            </td>
        </tr>
        """

    html = f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:700px;margin:0 auto;color:#1a1a1a;">
        <div style="background:linear-gradient(135deg,#0a66c2,#004182);padding:24px 32px;border-radius:8px 8px 0 0;">
            <h1 style="color:white;margin:0;font-size:22px;">LinkedIn Topic Suggestions</h1>
            <p style="color:#b3d4fc;margin:4px 0 0 0;font-size:14px;">{date_str} &middot; {len(topics)} topics</p>
        </div>

        <div style="padding:16px 32px;background:#f0f7ff;border:1px solid #e5e7eb;border-top:none;">
            <p style="margin:0;font-size:14px;color:#444;">
                Review these topic ideas. Reply with which ones you'd like drafted, or add your own.
            </p>
        </div>

        <div style="padding:0;background:#fff;border:1px solid #e5e7eb;border-top:none;">
            <table style="width:100%;border-collapse:collapse;font-size:14px;">
                {topic_rows}
            </table>
        </div>

        <div style="padding:16px 32px;background:#f8fafc;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;font-size:12px;color:#6b7280;">
            Generated by LinkedIn Post Automation &middot; Powered by Agentway
        </div>
    </div>
    """

    try:
        result = resend.Emails.send({
            "from": config.resend_from_email,
            "to": config.resend_to_email,
            "subject": f"LinkedIn Topics — {len(topics)} Suggestions ({date_str})",
            "html": html,
        })
        email_id = result.get("id", "ok") if isinstance(result, dict) else str(result)
        print(f"[EMAIL] Topics sent: {email_id} -> {', '.join(config.resend_to_email)}")
    except Exception as e:
        print(f"[EMAIL] Failed to send topics: {e}")


def _post_to_html(text: str) -> str:
    """Convert a LinkedIn post draft to simple HTML for email display."""
    # Escape HTML entities
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Bullet points
    text = re.sub(r"^[•*] (.+)$", r"&bull; \1", text, flags=re.MULTILINE)
    return text
